# -*- coding: utf-8 -*-
"""Интерфейс для записи рецепта в БД.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6E60Hj_zvrhNII02s_MmkpiXvMKcxEJ
"""



import streamlit as st
import json
import pandas as pd
from datetime import datetime

#убираем предупреждение
st.set_option('client.showErrorDetails', False)


st.set_page_config(page_title="Мои ПП Рецепты", page_icon="🍳")

def main():
    st.title("📖 База моих ПП рецептов")

    tab1, tab2, tab3 = st.tabs(["📝 Добавить рецепт", "📊 Просмотреть рецепты", "💾 Экспорт"])

    with tab1:
        add_recipe_form()

    with tab2:
        view_recipes()

    with tab3:
        export_data()

def add_recipe_form():
    with st.form("recipe_form", clear_on_submit=True):
        st.subheader("Добавить новый рецепт")

        # Основная информация
        col1, col2 = st.columns(2)
        with col1:
            name = st.text_input("Название рецепта*")
            category = st.selectbox("Категория*", ["", "завтрак", "обед", "ужин", "салат", "суп", "десерт", "перекус"])
            cooking_time = st.number_input("Время готовки (мин)*", min_value=1, max_value=300)

        with col2:
            cuisine = st.selectbox("Кухня", ["", "русская", "средиземноморская", "азиатская", "европейская", "мексиканская"])
            difficulty = st.select_slider("Сложность", ["легко", "средне", "сложно"])
            servings = st.number_input("Количество порций", min_value=1, max_value=10, value=2)

        # Ингредиенты
        st.subheader("Ингредиенты")
        ingredients = []

        ing_col1, ing_col2, ing_col3, ing_col4 = st.columns([3, 1, 1, 2])
        with ing_col1:
            ing_name = st.text_input("Название ингредиента")
        with ing_col2:
            ing_amount = st.number_input("Количество", min_value=0.0, step=0.5)
        with ing_col3:
            ing_unit = st.selectbox("Ед.изм", ["г", "мл", "шт", "ст.л.", "ч.л.", "стакан", "щепотка"])
        with ing_col4:
            ing_category = st.selectbox("Категория", ["крупы", "овощи", "фрукты", "белки", "жиры", "молочка", "специи"])

        if st.button("➕ Добавить ингредиент") and ing_name:
            ingredients.append({
                "name": ing_name,
                "amount": ing_amount,
                "unit": ing_unit,
                "category": ing_category
            })
            st.success(f"Добавлен: {ing_name}")

        # Показать добавленные ингредиенты
        if ingredients:
            st.write("**Добавленные ингредиенты:**")
            for i, ing in enumerate(ingredients):
                st.write(f"{i+1}. {ing['amount']} {ing['unit']} {ing['name']} ({ing['category']})")

        # Инструкция
        st.subheader("Инструкция приготовления")
        instructions = st.text_area(
            "Опишите шаги приготовления*",
            placeholder="Каждый шаг с новой строки:\n1. Шаг первый...\n2. Шаг второй...",
            height=150
        )

        # Питательная ценность
        st.subheader("Питательная ценность (на порцию)")
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            calories = st.number_input("Калории*", min_value=0, value=250)
        with col2:
            protein = st.number_input("Белки (г)", min_value=0.0, value=0.0)
        with col3:
            carbs = st.number_input("Углеводы (г)", min_value=0.0, value=0.0)
        with col4:
            fats = st.number_input("Жиры (г)", min_value=0.0, value=0.0)

        # Диетические теги
        st.subheader("Диетические характеристики")
        dietary_tags = st.multiselect(
            "Теги",
            ["высокобелковый", "низкоуглеводный", "низкожировой", "без глютена",
             "без лактозы", "вегетарианский", "веганский", "низкокалорийный"]
        )

        # Сохранение
        if st.form_submit_button("💾 Сохранить рецепт"):
            if not name or not category or not instructions:
                st.error("Заполните обязательные поля (отмечены *)")
            else:
                recipe = {
                    "name": name,
                    "category": category,
                    "cuisine": cuisine,
                    "difficulty": difficulty,
                    "servings": servings,
                    "cooking_time": cooking_time,
                    "ingredients": ingredients,
                    "instructions": [inst.strip() for inst in instructions.split('\n') if inst.strip()],
                    "nutrition": {
                        "calories": calories,
                        "protein": protein,
                        "carbs": carbs,
                        "fats": fats
                    },
                    "dietary_tags": dietary_tags,
                    "created_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }

                save_recipe(recipe)
                st.success("✅ Рецепт успешно сохранен!")

def save_recipe(recipe):
    """Сохраняем рецепт в JSON файл"""
    try:
        with open('my_recipes.json', 'r', encoding='utf-8') as f:
            recipes = json.load(f)
    except FileNotFoundError:
        recipes = []

    recipes.append(recipe)

    with open('my_recipes.json', 'w', encoding='utf-8') as f:
        json.dump(recipes, f, ensure_ascii=False, indent=2)

def view_recipes():
    st.subheader("Сохраненные рецепты")
    try:
        with open('my_recipes.json', 'r', encoding='utf-8') as f:
            recipes = json.load(f)

        if not recipes:
            st.info("Пока нет сохраненных рецептов")
            return

        for i, recipe in enumerate(recipes):
            with st.expander(f"🍳 {recipe['name']} ({recipe['category']})"):
                col1, col2 = st.columns(2)
                with col1:
                    st.write(f"**Кухня:** {recipe.get('cuisine', 'не указано')}")
                    st.write(f"**Сложность:** {recipe['difficulty']}")
                    st.write(f"**Время:** {recipe['cooking_time']} мин")
                    st.write(f"**Порции:** {recipe['servings']}")

                with col2:
                    st.write(f"**Калории:** {recipe['nutrition']['calories']} ккал")
                    st.write(f"**Белки:** {recipe['nutrition']['protein']}г")
                    st.write(f"**Жиры:** {recipe['nutrition']['fats']}г")
                    st.write(f"**Углеводы:** {recipe['nutrition']['carbs']}г")

                st.write("**Ингредиенты:**")
                for ing in recipe['ingredients']:
                    st.write(f"- {ing['amount']} {ing['unit']} {ing['name']}")

                st.write("**Инструкция:**")
                for j, step in enumerate(recipe['instructions']):
                    st.write(f"{j+1}. {step}")

                if recipe['dietary_tags']:
                    st.write("**Теги:** " + ", ".join(recipe['dietary_tags']))

    except FileNotFoundError:
        st.info("Файл с рецептами не найден")

def export_data():
    st.subheader("Экспорт данных")

    try:
        with open('my_recipes.json', 'r', encoding='utf-8') as f:
            recipes = json.load(f)

        if not recipes:
            st.info("Нет данных для экспорта")
            return

        # JSON экспорт
        st.download_button(
            label="📥 Скачать JSON",
            data=json.dumps(recipes, ensure_ascii=False, indent=2),
            file_name="my_recipes.json",
            mime="application/json"
        )

        # CSV экспорт (упрощенный)
        df_data = []
        for recipe in recipes:
            df_data.append({
                'name': recipe['name'],
                'category': recipe['category'],
                'cooking_time': recipe['cooking_time'],
                'calories': recipe['nutrition']['calories'],
                'ingredients_count': len(recipe['ingredients']),
                'dietary_tags': ', '.join(recipe['dietary_tags'])
            })

        if df_data:
            df = pd.DataFrame(df_data)
            st.download_button(
                label="📊 Скачать CSV",
                data=df.to_csv(index=False, encoding='utf-8'),
                file_name="my_recipes.csv",
                mime="text/csv"
            )

    except FileNotFoundError:
        st.info("Нет данных для экспорта")

if __name__ == "__main__":
    main()

